// WHAT ONE VOICE PUTS OUT, in the codes the DAC would have been handed, with
// nothing summed in front of the measurement.
//
// The level question is per voice. CVOutput hands each oscillator a share of
// the output span, and whether a shape spends that share, overruns it, or
// leaves most of it unused is a property of the shape alone -- summing voices
// first only hides it. So AssignVoices sets the shares, which keeps the
// calibration in voice.h where it is enforced, and then ONE oscillator renders
// into a zeroed buffer.
//
// DRONE: a level is a sustained quantity, so the gain envelope is held at its
// peak rather than struck. mixtest is where the onset is measured.
//
// `at rail` is the fraction of samples within one code of the share, and it
// means different things per shape: for a pulse or a saw the rail is where the
// waveform lives, and only for the resonant and noise shapes does it read as
// clipping. Compare it across settings of ONE shape, not between shapes.
//
// Usage: ./leveltest [shape=N] [voices=N] [pitch=MIDI] [timbre=0..127]
//                    [seconds=N] [seed=0xN]
//        ./leveltest table [voices=N] ...   every shape, one line each
#define TEST 1
#define private public
#include "yarns/voice.h"
#include "tools/cvtest/dac_stub.h"
#include "tools/panel_chain.h"
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <cmath>

namespace stmlib { uint32_t Random::rng_state_ = 0x21; }

using namespace yarns;
using namespace stmlib;

namespace {

// The hungriest layout's audio voice count bounds what a share can be split
// into; voice.h owns the number.
Voice voices[kMaxAudioVoices];
CVOutput audio_output;
ADSR adsr;

int OptInt(int argc, char** argv, const char* key, int fallback) {
  size_t n = strlen(key);
  for (int i = 1; i < argc; ++i) {
    if (!strncmp(argv[i], key, n) && argv[i][n] == '=') {
      return static_cast<int>(strtol(argv[i] + n + 1, NULL, 0));
    }
  }
  return fallback;
}

struct Level {
  double rms, peak, share, clamp;
  double capped_fraction;
};

Level Measure(int shape, int voices_assigned, int pitch, int knob,
              int seconds, int seed) {
  Random::Seed(static_cast<uint32_t>(seed));
  for (int v = 0; v < voices_assigned; ++v) voices[v].Init();
  audio_output.Init(true);
  for (int v = 0; v < voices_assigned; ++v) {
    voices[v].set_oscillator_mode(OSCILLATOR_MODE_DRONE);
    voices[v].set_oscillator_shape(static_cast<uint8_t>(shape));
    voices[v].set_timbre_init(static_cast<uint8_t>(knob));
    voices[v].timbre_init_current_ = voices[v].timbre_init_target_;
  }
  audio_output.AssignVoices(&voices[0], DC_PITCH,
                            static_cast<uint8_t>(voices_assigned),
                            static_cast<uint8_t>(voices_assigned));
  adsr.peak_u16 = UINT16_MAX;
  adsr.sustain_u16 = UINT16_MAX;
  adsr.attack_u32 = PanelStageIncrement(0, 0, 0);
  adsr.decay_u32 = PanelStageIncrement(0, 0, 0);
  adsr.release_u32 = PanelStageIncrement(64, 0, 0);
  voices[0].NoteOn(static_cast<int16_t>(pitch << 7), 100, 0, 0, true, adsr, 0,
                   0, PanelChiffAudibleSamples(67, 0, 0));

  Oscillator* osc = voices[0].oscillator();
  const OscillatorShape osc_shape = static_cast<OscillatorShape>(shape);
  Level out;
  // What this shape may reach. WHISTLE's voices add in power and it takes the
  // incoherent share for its level law; every other shape takes the coherent
  // one. The firmware keeps the incoherent share only as a u15, so the codes
  // it stands for are reconstructed here rather than held for this.
  const uint32_t scale_u15 = osc_shape == OSC_SHAPE_WHISTLE
      ? osc->incoherent_scale_u15_ : osc->coherent_scale_u15_;
  out.share = static_cast<double>(scale_u15) * INT16_MAX / 32768.0;
  out.clamp = osc->coherent_scale_codes_u16_;
  const int32_t at_rail = static_cast<int32_t>(out.clamp) - 1;

  double sum_squares = 0;
  long n = 0, capped = 0;
  int32_t peak = 0;
  for (long b = 0; b < static_cast<long>(kFrameHz) * seconds / kAudioBlockSize;
       ++b) {
    int16_t mix[kAudioBlockSize];
    memset(mix, 0, sizeof(mix));
    voices[0].Refresh();
    osc->Render(mix);
    for (size_t i = 0; i < kAudioBlockSize; ++i) {
      const int32_t s = mix[i];
      sum_squares += static_cast<double>(s) * s;
      ++n;
      const int32_t magnitude = s < 0 ? -s : s;
      if (magnitude > peak) peak = magnitude;
      if (magnitude >= at_rail) ++capped;
    }
  }
  out.rms = sqrt(sum_squares / n);
  out.peak = peak;
  out.capped_fraction = static_cast<double>(capped) / n;
  return out;
}

// Generated by build.sh from the enum, so an added or reordered shape cannot
// leave the labels off by one.
#include "shape_names.h"

}  // namespace

int main(int argc, char** argv) {
  const int voices_assigned = OptInt(argc, argv, "voices", 1);
  const int pitch = OptInt(argc, argv, "pitch", 60);
  const int knob = OptInt(argc, argv, "timbre", 127);
  const int seconds = OptInt(argc, argv, "seconds", 20);
  const int seed = OptInt(argc, argv, "seed", 0x21);
  const bool table = argc > 1 && !strcmp(argv[1], "table");

  printf("%d voice(s), MIDI %d, TIMBRE %d, %ds, seed %#x\n",
         voices_assigned, pitch, knob, seconds, seed);
  printf("  %-18s %8s %8s %8s %8s %8s\n",
         "shape", "dB/share", "rms", "peak", "peak/sh", "at rail");
  const int first = table ? 0 : OptInt(argc, argv, "shape", OSC_SHAPE_WHISTLE);
  const int last = table ? kOscShapeLast - 1 : first;
  for (int shape = first; shape <= last; ++shape) {
    const Level level =
        Measure(shape, voices_assigned, pitch, knob, seconds, seed);
    printf("  %-18s %+8.2f %8.0f %8.0f %8.3f %7.2f%%\n",
           kShapeNames[shape], 20 * log10(level.rms / level.share), level.rms, level.peak,
           level.peak / level.share, 100 * level.capped_fraction);
  }
  return 0;
}
