// A DISCONTINUITY IS A STEP THE SIGNAL'S OWN BANDWIDTH CANNOT PRODUCE.
//
// The class of fault this catches is the one a golden cannot: a break that is
// correct sample by sample against a recording taken from the same broken
// build. Here the reference is arithmetic instead. A run whose peak is A and
// whose highest partial is at f can move at most A * 2*pi*f/fs in one sample,
// so a step far above that came from something other than the waveform --
// a gain that stepped at a block edge, a state rescaled out from under a
// filter, an accumulator that wrapped.
//
// SO IT APPLIES TO THE NARROWBAND SHAPES ONLY. A band-limited saw or pulse
// steps its whole amplitude at an edge because that is the waveform; measured
// against this bound every one of them reads 50x to 100x and always will. The
// resonator shapes are the ones whose output really is narrowband, and they are
// the ones this can speak about.
//
// The excitation is noise, which is not narrowband either, so the multiple
// below still buys room and only a real break exceeds it. This is a SMOKE
// ALARM, not a measurement: the ratio is against the bound, 1.0 is the bound,
// and the number to watch is a shape moving from where it sat before.
//
// It sweeps the corners a break has actually been found at: several voices
// struck at once from cold, the chiff at its extremes, and TIMBRE MOD ENVELOPE
// signed both ways.
//
// WHAT IT ALREADY ANSWERED, so that nobody pays for the answer twice: the
// WHISTLE attack glitch is NOT a sample-step discontinuity. Run against
// `4d3a444f`, which the user calls clean, WHISTLE reads 60.4 where the build
// they call glitchy reads 2.15, and every one of the worst cells moves the same
// way by 20x to 30x at MATCHED settings. The hard CONSTRAIN that build capped
// the state with is a real discontinuity and the knee removed it, so both
// numbers are correct and the ear disagrees with both. Look for the glitch in
// something this cannot see.
//
// Usage: ./steptest [verbose]
#define TEST 1
#define private public
#include "yarns/voice.h"
#include "tools/cvtest/dac_stub.h"
#include "tools/panel_chain.h"
// Generated by build.sh from the enum.
#include "../leveltest/shape_names.h"
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <cmath>

namespace stmlib { uint32_t Random::rng_state_ = 0x21; }

using namespace yarns;
using namespace stmlib;

namespace {

const uint8_t kVoices = 4;

Voice voices[kVoices];
CVOutput audio_output;
ADSR adsr;

const int kPitches[] = { 24, 48, 60, 84, 108, 120 };
const int kKnobs[] = { 0, 32, 64, 96, 127 };
const int kTimbreMods[] = { INT16_MIN, 0, INT16_MAX };
const int kChiffAmounts[] = { 0, 64, 127 };
const int kSounding[] = { 1, 2, 4 };
// A chord, so the voices are at different pitches and their peaks land at
// different times -- one note four times over cannot show a sum breaking.
const int kIntervals[] = { 0, 7, 12, 16 };
// The onset and the ring after it. Breaks have all been at the onset.
const long kSamples = kFrameHz / 2;
// The attack the user reports the break at.
const int kAttack = 12;
// Room for the excitation's own bandwidth above the narrowband bound, and a
// floor in codes so a near-silent run does not divide its way to a huge ratio.
const double kBandwidthAllowance = 4.0;
const double kQuietFloorCodes = 8.0;

int16_t rendered[kSamples];

double WorstStep(int shape, int pitch, int knob, int timbre_mod,
                 int chiff, int sounding, double* peak_out) {
  Random::Seed(0x21);
  for (int v = 0; v < kVoices; ++v) voices[v].Init();
  audio_output.Init(true);
  for (int v = 0; v < kVoices; ++v) {
    voices[v].set_oscillator_mode(OSCILLATOR_MODE_ENVELOPED);
    voices[v].set_oscillator_shape(static_cast<uint8_t>(shape));
    voices[v].set_timbre_init(static_cast<uint8_t>(knob));
    voices[v].timbre_init_current_ = voices[v].timbre_init_target_;
  }
  audio_output.AssignVoices(&voices[0], DC_PITCH, kVoices, kVoices);
  PanelAdsr(&adsr, kAttack, 64, 60, 64, 0, 100, 0, 0, 0, 0);
  for (int v = 0; v < sounding; ++v) {
    voices[v].NoteOn(
        static_cast<int16_t>((pitch + kIntervals[v]) << 7), 100, 0, 0, true,
        adsr, static_cast<int16_t>(timbre_mod),
        PanelChiffAmount_q30(chiff, 0, 0), PanelChiffAudibleSamples(67, 0, 0));
  }

  const uint16_t zero = audio_output.zero_dac_code_;
  long n = 0;
  for (long b = 0; b < kSamples / kAudioBlockSize; ++b) {
    for (int v = 0; v < kVoices; ++v) voices[v].Refresh();
    audio_output.RenderSamples(0, 0, 0);
    for (size_t i = 0; i < kAudioBlockSize; ++i) {
      rendered[n++] = static_cast<int16_t>(
          static_cast<uint16_t>(g_dac_block[0][i]) - zero);
    }
  }

  // Two passes: the bound is the run's OWN peak, so an early sample is not
  // measured against a peak the run has not reached yet.
  double peak = 0;
  for (long i = 0; i < n; ++i) {
    if (fabs(static_cast<double>(rendered[i])) > peak) {
      peak = fabs(static_cast<double>(rendered[i]));
    }
  }
  // The highest note sounding sets the fastest legitimate slew.
  const double top_hz = 440.0 * pow(
      2.0, (pitch + kIntervals[sounding - 1] - 69) / 12.0);
  const double allowed = kBandwidthAllowance * peak * 2.0 * M_PI * top_hz
      / kFrameHz + kQuietFloorCodes;
  double worst = 0;
  for (long i = 1; i < n; ++i) {
    const double step = fabs(
        static_cast<double>(rendered[i]) - rendered[i - 1]);
    if (step / allowed > worst) worst = step / allowed;
  }
  *peak_out = peak;
  return worst;
}

}  // namespace

int main(int argc, char** argv) {
  const bool verbose = argc > 1 && !strcmp(argv[1], "verbose");
  int failures = 0;
  printf("  %-24s %8s %28s\n", "shape", "worst", "at");
  // HIGH-PASS PING passes the exciter above the note at unity, and the exciter
  // is a chiff -- broadband, so the bound has nothing to say about it. It reads
  // 88x, which is what that looks like.
  const int narrowband[] = {
    OSC_SHAPE_WHISTLE, OSC_SHAPE_PING_BP, OSC_SHAPE_PING_LP };
  for (size_t si = 0; si < sizeof(narrowband) / sizeof(*narrowband); ++si) {
    const int shape = narrowband[si];
    double worst = 0, worst_peak = 0;
    int wp = 0, wk = 0, wm = 0, wc = 0, ws = 0;
    for (size_t p = 0; p < sizeof(kPitches) / sizeof(*kPitches); ++p)
    for (size_t k = 0; k < sizeof(kKnobs) / sizeof(*kKnobs); ++k)
    for (size_t m = 0; m < sizeof(kTimbreMods) / sizeof(*kTimbreMods); ++m)
    for (size_t c = 0; c < sizeof(kChiffAmounts) / sizeof(*kChiffAmounts); ++c)
    for (size_t s = 0; s < sizeof(kSounding) / sizeof(*kSounding); ++s) {
      double peak = 0;
      const double here = WorstStep(shape, kPitches[p], kKnobs[k],
                                    kTimbreMods[m], kChiffAmounts[c],
                                    kSounding[s], &peak);
      if (verbose) {
        printf("%d %d %d %d %d %d %.4f %.0f\n", shape, kPitches[p], kKnobs[k],
               kTimbreMods[m], kChiffAmounts[c], kSounding[s], here, peak);
      }
      if (here > worst) {
        worst = here; worst_peak = peak;
        wp = kPitches[p]; wk = kKnobs[k]; wm = kTimbreMods[m];
        wc = kChiffAmounts[c]; ws = kSounding[s];
      }
    }
    printf("  %-24s %8.3f   MIDI %3d knob %3d mod %6d chiff %3d x%d  peak %.0f\n",
           kShapeNames[shape], worst, wp, wk, wm, wc, ws, worst_peak);
    (void) failures;
  }
  return 0;
}
